# Site settings
title: "Thursday's Flight"
email: thursdaysflightband@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official website for the band Thursday's Flight - Rock music from Holly Springs, NC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Band settings
band_name: "Thursday's Flight"
band_location: "Holly Springs, NC"
band_genre: "Rock"
band_description: "Thursday's Flight is based in Holly Springs, NC and is available for private parties as well as charity and community events. We perform original music as well as covers from the 70's, 80's, 90's, and 2000's."

# Social media links
social_links:
  facebook: "https://facebook.com/thursdaysflight"
  youtube: "https://youtube.com/@thursdaysflight"
  spotify: "https://open.spotify.com/artist/5vxonuiriqJsHAng1e8EFf"
  apple_music: "https://music.apple.com/us/artist/thursdays-flight/1203786498"

# Music links
music_links:
  spotify_artist: "thursdaysflight"
  apple_music_artist: "thursdaysflight"

# User setting
owner:
email: "thursdaysflightband@gmail.com"
youtube_channel: "@thursdaysflight"
hyperfollow_url: "thursdaysflight/almost-there"
facebook_page: "thursdaysflight"
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright: "Thursday's Flight"

# API settings
google_api_key:

# Build settings
markdown: kramdown
